#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
raet floscript runner CLI

Runs floscript plan from command line shell

example:
raetflo -h
raetflo -V
raetflo -v concise -n raet -r -f ../raet/flo/plan/raet.flo -b raet.flo.behaving
raetflo -v verbose -n raet -r -p 0.0625 ../raet/flo/plan/raet.flo -b raet.flo

'''

# Import python libs
import sys

# Import ioflo libs
import ioflo.app.run


def main():
    '''
    Main entry point for ioflo CLI
    '''
    args = ioflo.app.run.parseArgs()

    ioflo.app.run.run(  name=args.name,
                        period = float(args.period),
                        real = args.realtime,
                        filepath = args.filename,
                        behaviors=args.behaviors,
                        username=args.username,
                        password=args.password,
                        verbose = args.verbose,
                        consolepath=args.console,
                        statistics=args.statistics)

if __name__ == '__main__':
    main()
